### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by robin3** [ng-vu/tomato#2]
I'm having trouble installing this in BTT.

I've downloaded the pre-built command, configured the web server as specified, copied the widget and the button (so that the switch button, the red tomato and 00:00 are visible).

1. What do I do with tomato.dms which was downloaded?
2. When I try to start tomato from the terminal, it responds with "tomato: command not found"

Sorry this is such a basic question. I've used a little Apple Script to create other BTT widgets, but I'm not a developer.

**Comment by iOliverNguyen** [comment]
Hi robin3,

1. Which `tomato.dms` did you download? The pre-built command is located at https://github.com/ng-vu/tomato/raw/master/others/tomato

2. I recommend creating a directory called `bin` in your home directory: `/Users/<your_user_name>/bin`. Copy the pre-built command into `bin` and you can run it by typing `~/bin/tomato` in the terminal.

To start the command everytime you log in, you should use Automator.app (follow [the instruction here](https://stackoverflow.com/questions/6442364/running-script-upon-login-mac)).

**Comment by robin3** [comment]
Thanks. I've got it working now. Identified 3 issues along the way:

1. When downloading the pre-built command via Safari, a .dms file extension is (wrongly) appended by safari. This doesn't happen when downloading in Chrome.

2. It's necessary to run `chmod +x ~/bin/tomato` in the terminal in order to convert the prebuilt command into an executable file

3. Copying the config for the widget via cmd-v (see step 3 in the instructions) sets the widget as "Run *Shell* Script..." instead of "Run *Applescript*..."

**Comment by iOliverNguyen** [comment]
Thanks for your feedback. I've updated the README.

About 3., I've tested copying the widget via cmd-V and BTT set it correctly to "_Run Apple Script (blocking)_". I'm not sure how you got "_Run Shell Script..._".

**Comment by bzx** [comment]
To solve the problem of auto-starting the webserver, I did the following:

- the "tomato" executable went into /usr/local/bin just to keep things tidy
- created Automator application with "Run Shell Script" action with the following 2 lines:
`export PATH=/usr/local/bin:$PATH`
`tomato -uuid=4FB70D65-DB91-45AD-A604-E772C2BBB540 -port=12345`
(the first line is important as the Automator search path does not include the /usr/local/bin, according to [this post at StackExchange](https://apple.stackexchange.com/questions/97502/my-automator-workflow-fails-because-it-fails-to-find-the-git-command-within-the).
- save Automator application as "BTT Tomato Webserver.app" and drag it over to /Applications 
- open System Prefs → Users & Groups, and in "Login Items" tab, add the above app to the list.

et voila!

<img width="614" alt="screenshot 2019-02-06 at 22 05 04" src="https://user-images.githubusercontent.com/654500/52373860-1047a780-2a5c-11e9-90cf-e760055e9477.png">

<img width="452" alt="screenshot 2019-02-06 at 22 11 35" src="https://user-images.githubusercontent.com/654500/52373906-2c4b4900-2a5c-11e9-9cee-a8b1568ad3cd.png">

**Comment by bzx** [comment]
I had some trouble getting this to work upon system restart and new login (was getting an error from Automator). I don't understand why, as Automator was actually starting the tomato server, and not BTT... however I added a delay before starting the Automator script:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/654500/52469160-fe185700-2b8a-11e9-92da-aa2d4717f8e2.png">

**Comment by bzx** [comment]
One more thing I totally don't understand is: why the tomato starts on port 12345, and the BTT is trying to connect to port 12321...

**Comment by iOliverNguyen** [comment]
Hi Tom,

The default working command is `tomato -uuid=[UUID] -port=12345 -listen=:12321`. That means:

- Tomato server **listen**s on `:12321` and will connect to BTT on **port** `12345`
- BTT should listen on port `12345` and connect to tomato server on port `12321`.

Hope this makes things more clear.

**Comment by Dom-J** [comment]
Hi,
So, I got all this work, great stuff!
Two questions:
1. Does the terminal have to be opened and running the server all the time? 🤔 I managed to start the server by making a BTT button that starts it (so without opening the terminal), but it will shut itself down again after 3min or so.
2. Isn't there a way to add the code from the tomato server inside BTT? I think it would be way smarter and way more people would actually use these great widgets and buttons you made!

**Comment by Caliguvara** [comment]
Hi,
So I managed to get this all running, great stuff! **Two questions** though:

1. **Does the terminal really have to be open to run the server**, or did I miss something? This kinda annoys me, and I created a BTT Button that launches the server by executing
`do shell script "/Users/your_user_here/bin/tomato"`
but it will shut itself down after 3min or so, causing the Pomodoro to end. Hmmmmmmm 🤔 
2. Ain't there a way to **get the code directly inside BTT** without the need of handling an external file? I think this would be much nicer, especially as many users are not very experienced with coding or the terminal. I think your work would be even more solicited if there was an "easier" way to install it!

Impatient to hear from you!
Thanks for your great work!
~_Caliguvara_

**Comment by iOliverNguyen** [comment]
Hi Caliguvara,

1. You don't need the terminal to run the server. As mentioned in the README, you should use Automator.app to start the command every time you login (follow [the instruction here](https://stackoverflow.com/questions/6442364/running-script-upon-login-mac)).

2. Scheduling time is a complicated task and I can not manage to implement it using Apple script or bash script to run directly inside BTT. If I have time, I may rewrite it in Swift and run it as a native tool on Mac. It may be the best compromise.

**Comment by iOliverNguyen** [comment]
In the meantime, you may want to check https://github.com/Toxblh/MTMR. It already includes a Pomodoro plugin.

**Comment by bzx** [comment]
@Caliguvara just see my above post to see how you can easily start the server at login https://github.com/ng-vu/tomato/issues/2#issuecomment-461188060

**Comment by jiaqiwang-byte** [comment]
Hi,
I Have a problem,when I running clock i find the bettertouchtool tomato icon was always jump to 00:00,I wender know why and how to fix it,thank you.
